name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    # runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
          java-version: 1.17
    - name: Build plugin
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        arguments: buildPlugin --stacktrace -PintellijPublishToken=none
    - name: dotnet-tests-report
      uses: zyborg/dotnet-tests-report@v1.3.0
      with:
        report_name: plugin_tests
        report_title: Plugin Tests
        set_check_status_from_test_outcome: true
        project_path: src/dotnet/ReSharperPlugin.NSubstituteComplete.Tests/ReSharperPlugin.NSubstituteComplete.Tests.csproj
        github_token: ${{ secrets.GITHUB_TOKEN }}

