name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Build plugin
      uses: eskatos/gradle-command-action@v1.4.0
      with:
        arguments: buildPlugin --stacktrace
    - name: dotnet-tests-report
      uses: zyborg/dotnet-tests-report@v1.4.4
      with:
        report_name: plugin_tests
        report_title: Plugin Tests
        set_check_status_from_test_outcome: true
        project_path: src/dotnet/ReSharperPlugin.NSubstituteComplete.Tests/ReSharperPlugin.NSubstituteComplete.Tests.csproj
        github_token: ${{ secrets.GITHUB_TOKEN }}

